<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_getTransactionOverview</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>802267d3-9143-46e0-94ba-37b5c3b4731f</testSuiteGuid>
   <testCaseLink>
      <guid>f445458c-6bbb-414f-894b-7d4826a0a3db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC_loginCustomer/TC_login081266483909</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47070cee-9204-4cd3-9733-c2b2d22c0ab3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86335d3c-b14e-471d-bc26-42fcf8622710</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f19ee28-37e8-46df-9b23-23ff1f1920eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c77a149-f0c6-4e9a-ae68-04627f364b23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79b85f76-778a-41a0-9433-89669ac27106</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77676cb-0a01-4aba-990d-1986efd561f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c989e74a-cc29-4efe-b712-6ea550c9f270</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abdc72c6-56d6-4bf2-8a22-04287053b659</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a762eb4-d995-4b71-9be5-d07088d579c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/E_Wallet/TC_getTransactionOverview/TC_getTransactionOverview</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f61c393a-8a0b-4560-b325-b5e57a06cd53</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/E_Wallet/DF_getTransactionOverview/DF_getTransactionOverview</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>f61c393a-8a0b-4560-b325-b5e57a06cd53</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_rc</value>
         <variableId>66b88f90-ffb3-4cab-bdb9-aa44f194b3b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f61c393a-8a0b-4560-b325-b5e57a06cd53</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>customer_token</value>
         <variableId>09431a90-3d65-4d0c-b532-8729fb147dfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86a0d389-c94a-4a9b-9347-48e0bbbfc81e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e21fa43-b6d6-4b57-9900-a3fa499051a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33092056-8efe-42c4-807a-b460679cc7c2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
