<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_getSubscriptionPackage</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1b98c723-5fa4-489d-a479-0e3ee6aa3bf2</testSuiteGuid>
   <testCaseLink>
      <guid>b672febc-3feb-471d-ab86-203571e3388b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC_loginMerchant/TC_loginMerchantArchie</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c47b940-c9ea-4cd5-979b-b97fe1b30ab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23436f56-c5c2-4b17-95c5-f7e053a622a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>996b7b31-5704-4f9d-a457-621f74ba7b61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b307803-d5ce-458a-a38a-64ceec7f8573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a71ec4e3-12ff-4388-a885-b5e8f82761e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cb5ce35-6360-4f02-b1be-80550b7ab426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0aa8e5a-890c-4e63-97de-5192c04bdc2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cf89daf-e71f-4f2a-b57b-b0cee98249de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f96be35-2ffe-4a33-b73e-86bbac38cc7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_App/TC_getSubscriptionPackage/TC_getSubscriptionPackage</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ec2852a6-8b85-44e5-90ce-1194ac8d455d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/Dashboard_App/DF_getSubscriptionPackage/DF_getSubscriptionPackage</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ec2852a6-8b85-44e5-90ce-1194ac8d455d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_rc</value>
         <variableId>a83e6eb4-a3fb-4fbd-b1ff-131d61341be4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f874dc13-ad93-46ec-9e31-df292ce4a1c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32e2c378-f501-40a6-b2d9-87f99c7cff4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>601e68f3-d5a0-4f6e-83d5-e5d33c2c30c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ec2852a6-8b85-44e5-90ce-1194ac8d455d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>organisation_id</value>
         <variableId>d2115e4d-8e7b-441b-93de-8406cb7c1dcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ec2852a6-8b85-44e5-90ce-1194ac8d455d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lang</value>
         <variableId>f042009e-254b-4d76-9387-234472f3a257</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ec2852a6-8b85-44e5-90ce-1194ac8d455d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>merchant_token</value>
         <variableId>0fe581c3-477b-4432-b58d-12adb04913c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ec2852a6-8b85-44e5-90ce-1194ac8d455d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>partner_token</value>
         <variableId>8190e3b5-2e97-400b-81ff-cc9adfcdec12</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
