<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Suite_Add_SoF_DKI</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c3fd1981-e951-4dbe-9efe-736906dd58cf</testSuiteGuid>
   <testCaseLink>
      <guid>992272ec-5dc5-4380-8796-91330f5c194f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC_loginCustomer/TC_login081266483909</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47070cee-9204-4cd3-9733-c2b2d22c0ab3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86335d3c-b14e-471d-bc26-42fcf8622710</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f19ee28-37e8-46df-9b23-23ff1f1920eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c77a149-f0c6-4e9a-ae68-04627f364b23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79b85f76-778a-41a0-9433-89669ac27106</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77676cb-0a01-4aba-990d-1986efd561f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c989e74a-cc29-4efe-b712-6ea550c9f270</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abdc72c6-56d6-4bf2-8a22-04287053b659</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a57236b7-a80d-4c1a-aec0-76c75dcb7b62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/E_Wallet/TC_addSoF/Add_SoF_DKI</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7bb82f3f-75f3-4265-b1f4-905fc929b18a</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/E_Wallet/DF_addSoF/DF_addSofDKI</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c630b65-d142-4293-a2ba-e83f97f92e04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3eb177f-fb9e-49b1-892e-ca0340cb4687</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba205d04-a370-4fa5-bef6-332b93be0097</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85741744-d450-4061-b4e0-15a347166de4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb153443-7c51-4016-9326-184ae3d9f4e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39f9189d-64f2-42eb-a10e-68127b8b2b27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7966ce5-fcae-4697-8f4a-6fea1c7e6998</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9a1d591-c0c2-4e21-bf79-314ff3b37cd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd249128-d723-4ae2-8030-6c3861fe073e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a2ed20f-5920-40e7-8f3b-5f3fc84993c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99f3c9a3-bd6a-4eca-95d9-45d0572d10d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6becfa8c-b841-484c-8c21-5ce8c4325735</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
