<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_rianProjectCheckAppVer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f2e2000a-8e02-4fed-ad7d-7a7923a8c062</testSuiteGuid>
   <testCaseLink>
      <guid>8b58f293-006e-4866-9d05-0117ac177b12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/E_Wallet/TC_checkAppVer/TC_checkAppVer</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>79058ffc-cfe8-432c-856e-e46e5413aebe</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/E_Wallet/DF_checkAppVersion/DF_checkAppVersion</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>79058ffc-cfe8-432c-856e-e46e5413aebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lang</value>
         <variableId>c92265c9-ddbd-460b-ab55-8477d476f284</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79058ffc-cfe8-432c-856e-e46e5413aebe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status_code</value>
         <variableId>2eef4133-fc3d-4aea-85f1-9bda046fa408</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b51ab2ac-1a73-49fc-a67f-eac42cc121a6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
