<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_checkURLTokenValidity</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>43df2449-4621-4736-944e-c37d7aa21be0</testSuiteGuid>
   <testCaseLink>
      <guid>c769391a-0085-46c6-8915-cf6c3360e6c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC_loginMerchant/TC_loginMerchantSysAdmin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af1991ef-8a4f-4f69-b505-8ec89593b820</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a1cc9d3-b52f-4b04-9f11-959bb42021eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3930fa3-e666-4c24-b0a2-881335c90d15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>018b455f-f75a-44a9-8ca8-379d1701dd58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bba9ed4-f5f5-43f7-8d45-c243e2c1e67e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4acf6338-a083-4ac5-9b6d-79d50fbd5e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0687c2c0-7739-4563-8379-f00e640a3fc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06fe1c75-c8ac-4090-896b-9ff161389c6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f96be35-2ffe-4a33-b73e-86bbac38cc7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_App/TC_checkURLTokenValidity/TC_checkURLTokenValidity</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ba90fe52-36f5-41c1-a6ed-864666a22a8c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/Dashboard_App/DF_checkURLTokenValidity/DF_checkURLTokenValidity</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ba90fe52-36f5-41c1-a6ed-864666a22a8c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_rc</value>
         <variableId>49eaa934-f91e-4efe-aac2-66fb6e4ebb96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>519ea0a4-68b7-4d32-8a2c-cc3c4fe6e6c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea85fc1a-8484-4c44-9488-bb752dfac607</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a63edd2-2774-432f-9ef5-81f3d1a03e1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba90fe52-36f5-41c1-a6ed-864666a22a8c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>merchant_token</value>
         <variableId>de9ea32d-92f5-4d29-81c6-2a463f71ed83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba90fe52-36f5-41c1-a6ed-864666a22a8c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>partner_token</value>
         <variableId>b41998fa-560d-436d-a1e6-f08273d5c642</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba90fe52-36f5-41c1-a6ed-864666a22a8c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>access_token</value>
         <variableId>3e6a5083-1c10-4e90-9b20-677069b03cd2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
