<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_getCustomerProfile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>624c7efd-ff89-47c6-9237-9c5d56c0e118</testSuiteGuid>
   <testCaseLink>
      <guid>9a8a36b3-223b-4ac7-baea-bc492241d125</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC_loginCustomer/TC_login081266483909</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47070cee-9204-4cd3-9733-c2b2d22c0ab3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86335d3c-b14e-471d-bc26-42fcf8622710</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f19ee28-37e8-46df-9b23-23ff1f1920eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c77a149-f0c6-4e9a-ae68-04627f364b23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79b85f76-778a-41a0-9433-89669ac27106</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77676cb-0a01-4aba-990d-1986efd561f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c989e74a-cc29-4efe-b712-6ea550c9f270</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abdc72c6-56d6-4bf2-8a22-04287053b659</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0765f17-e206-458c-a78f-59116ddab187</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/E_Wallet/TC_getCustomerProfile/TC_getCustomerProfile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1ac50dd7-3d4e-42aa-8c5c-34abf1ca849e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/E_Wallet/DF_getCustomerProfile/DF_getCustomerProfile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>1ac50dd7-3d4e-42aa-8c5c-34abf1ca849e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_rc</value>
         <variableId>51c075a2-7a74-4b2a-be7f-ca58e26a2376</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ac50dd7-3d4e-42aa-8c5c-34abf1ca849e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>customer_token</value>
         <variableId>fffe98b7-f029-498e-a0e6-61967a9da95d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c68fe03-f66b-4f80-94d0-d7f0292ba0a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5391cf6e-6419-4475-b876-7257240c9c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f34e47bd-6a6d-4d70-bfeb-5d98f52af60f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
