<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_getEnrollmentDetail</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5dfafdcc-e41e-4b95-8297-ad06c1db9693</testSuiteGuid>
   <testCaseLink>
      <guid>8edc987b-eaaa-45fd-ac89-df61c4767869</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC_loginOrganisation/TC_loginOrganisationSysAdmin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6d35a26-1f55-43bb-b4b9-4b192788588f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cee1edd-d721-4138-ba68-ac90e25d6de8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c973c5a-2306-497e-9e12-2ecb7274026d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6609408-1668-4f0c-9407-1274ebffad81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a7d2e6e-1829-4417-b47c-e302bec7a74e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffea2ad5-dbfe-41c1-a4c9-1b47efe1e270</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e877e39-2d75-469f-892d-aadcbde1b9fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25572c6b-7cd6-4da5-aba7-c78e842a540c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c512f71a-82a8-4d1d-b6b3-6ce02931a6bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d0e570f-0147-4326-8548-de280e2af736</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_App/TC_getEnrollmentDetil/TC_getEnrollmentDetil</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1b2f16db-2de0-4e59-bbd9-ae970f5cfc91</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Dashboard_App/DF_getEnrollmentDetil/DF_getEnrollmentDetil</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>1b2f16db-2de0-4e59-bbd9-ae970f5cfc91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user_agent</value>
         <variableId>21ced2ae-d074-432d-8538-c8c9bdc891df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1b2f16db-2de0-4e59-bbd9-ae970f5cfc91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>enrolment_id</value>
         <variableId>9492dd81-2917-4a34-914c-71477e9b3bfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1b2f16db-2de0-4e59-bbd9-ae970f5cfc91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_rc</value>
         <variableId>eeceb75b-4990-4ae2-8b6e-8c4d47015fad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>101820d8-94ed-48f3-9ac4-ce3c5782cc46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01d10d1d-0f1f-4b82-a73b-ca2109158cf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a61c306e-ece5-47ce-bdc7-843e67713704</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1b2f16db-2de0-4e59-bbd9-ae970f5cfc91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>organisation_id</value>
         <variableId>82a95676-2665-4ee5-8700-e7d0e5626141</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1b2f16db-2de0-4e59-bbd9-ae970f5cfc91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lang</value>
         <variableId>3e9ec91a-0f0b-4c78-94de-6f8ada6d0289</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1b2f16db-2de0-4e59-bbd9-ae970f5cfc91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>merchant_token</value>
         <variableId>06d4b89a-71ea-4a67-9ccb-37095b3b0c88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1b2f16db-2de0-4e59-bbd9-ae970f5cfc91</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>partner_token</value>
         <variableId>6bb68455-7fef-4b29-859e-a8c85d6611e5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
