<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_inquiryEnrollmentStatusMerchant</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8baa464d-b25b-4f0f-9aa9-08dc8db619c4</testSuiteGuid>
   <testCaseLink>
      <guid>98a31e65-ff7f-4316-a696-98036db8da84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Account/TC_loginOrganisation/TC_loginOrganisationSysAdmin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6d35a26-1f55-43bb-b4b9-4b192788588f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cee1edd-d721-4138-ba68-ac90e25d6de8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c973c5a-2306-497e-9e12-2ecb7274026d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6609408-1668-4f0c-9407-1274ebffad81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a7d2e6e-1829-4417-b47c-e302bec7a74e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffea2ad5-dbfe-41c1-a4c9-1b47efe1e270</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e877e39-2d75-469f-892d-aadcbde1b9fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25572c6b-7cd6-4da5-aba7-c78e842a540c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c512f71a-82a8-4d1d-b6b3-6ce02931a6bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d04cd6df-dc1d-41d0-9679-e25431a1fa59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC_loginMerchant/TC_loginMerchantStiles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e45cbeb6-ce25-4db2-a618-ecd73f4388ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93d01621-d3cb-4d4b-bcb4-fdd24be8f242</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e2bf09b-a327-4542-a871-db4c284f62cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08faa84b-8114-4352-b87d-ce8373add8a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ad257c1-89ab-49b2-b0be-cd59cb1971a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f6ee102-f493-4319-b338-e351c086626e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>985a2287-c1af-4420-9300-60e2b6f8da7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91a129af-0a66-408d-ab35-a33f19ff4bd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc1c9933-859f-4553-9c30-7330b7a2cb68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Account/TC_loginMerchant/TC_loginMerchantArchie</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c47b940-c9ea-4cd5-979b-b97fe1b30ab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23436f56-c5c2-4b17-95c5-f7e053a622a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>996b7b31-5704-4f9d-a457-621f74ba7b61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b307803-d5ce-458a-a38a-64ceec7f8573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a71ec4e3-12ff-4388-a885-b5e8f82761e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cb5ce35-6360-4f02-b1be-80550b7ab426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0aa8e5a-890c-4e63-97de-5192c04bdc2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cf89daf-e71f-4f2a-b57b-b0cee98249de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48719b85-8955-4a12-9134-4cf08b8fa9d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_App/TC_inquiryEnrollmentStatusMerchant/TC_inquiryEnrollmentStatusMerchant</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0433ac51-2bab-4b85-8662-797fa2c43fb2</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/Dashboard_App/DF_inquiryEnrollmentStatusMerchant/DF_inquiryEnrollmentStatusMerchant</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0433ac51-2bab-4b85-8662-797fa2c43fb2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user_agent</value>
         <variableId>8f2c3c74-2ae1-426b-bab8-376f51ff2573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0433ac51-2bab-4b85-8662-797fa2c43fb2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>enrolment_id</value>
         <variableId>523c7a4c-41ab-4613-9fb6-3603b33e5ebb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0433ac51-2bab-4b85-8662-797fa2c43fb2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>organisation_id</value>
         <variableId>997fa2d1-1abb-4867-bfd3-58c069a1a8e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0433ac51-2bab-4b85-8662-797fa2c43fb2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lang</value>
         <variableId>ffd94554-d3e8-4425-852a-acbbb133d1e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0433ac51-2bab-4b85-8662-797fa2c43fb2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_rc</value>
         <variableId>0ce4f4c7-3d3b-4dc7-bd4a-a234e867ab36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0433ac51-2bab-4b85-8662-797fa2c43fb2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>merchant_token</value>
         <variableId>5f62ae23-1738-46a3-b8d5-7af173f8ad5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a94c996b-3460-4d6e-a6e5-3821da09fd79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>631d9423-1f0a-434c-b1b4-89150aabfd74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01d97602-6002-464d-b113-a6085d2fc740</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0433ac51-2bab-4b85-8662-797fa2c43fb2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>partner_token</value>
         <variableId>b27b85dc-e4a6-4f11-b603-2569a9ea6c63</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
