<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_syncMerchant</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>acfbcfaa-7672-4f62-b37a-c143d7b56fb7</testSuiteGuid>
   <testCaseLink>
      <guid>ccb083ce-d293-445e-81b3-77a73e297fb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/E_Wallet/TC_syncMerchant1/TC_syncMerchant1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>eeb19fab-a42d-4fe1-b6d8-25f6fee481b8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/E_Wallet/DF_syncMerchant/DF_syncMerchant</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>eeb19fab-a42d-4fe1-b6d8-25f6fee481b8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>page</value>
         <variableId>d6524b8a-922d-460c-bc8d-e0431b765c86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eeb19fab-a42d-4fe1-b6d8-25f6fee481b8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>page_size</value>
         <variableId>22362a7a-2b44-4fff-95eb-700f4985a040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eeb19fab-a42d-4fe1-b6d8-25f6fee481b8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>date</value>
         <variableId>cd60dd2e-2ab5-4b19-a007-dc4a5981e583</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eeb19fab-a42d-4fe1-b6d8-25f6fee481b8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>rc</value>
         <variableId>ba4f5e43-5402-4fcc-ab84-5c987ac4380a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
